SET IDENTITY_INSERT [dbo].[StudentLog] ON
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2024, N'2020-02-28 13:16:36', N'Added', N'Ian', N'O''Loughlin', N'ian@mydbs.ie', NULL, N'81 Tolka Estate', NULL, N'Glasnevin', NULL, N'Dublin 11', NULL, N'Dublin', NULL, N'Undergrad', NULL, N'IT', 11111111)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2025, N'2020-02-28 13:17:26', N'Added', N'Lyn', N'O''Connor', N'lyn@gmail.com', NULL, N'49 Oldtown Avenue', NULL, N'Santry', NULL, N'Dublin 9', NULL, N'Dublin', NULL, N'Postgrad', NULL, N'Media', 33333333)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2026, N'2020-02-28 13:18:07', N'Added', N'Lily', N'McCarthy', N'lil@hotmail.com', NULL, N'17 The Estuary', NULL, N'', NULL, N'Waterford', NULL, N'Waterford', NULL, N'Undergrad', NULL, N'French', 44444444)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2027, N'2020-02-28 13:19:00', N'Added', N'Bryan', N'Mullins', N'bmul@yahoo.co.uk', NULL, N'41 Douglas Street', NULL, N'', NULL, N'Cork', NULL, N'Cork', NULL, N'Postgrad', NULL, N'Business', 88888888)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2028, N'2020-02-28 13:20:00', N'Added', N'Paul', N'Bridgeman', N'pb@gmail.com', NULL, N'Listowell', NULL, N'', NULL, N'', NULL, N'Kerry', NULL, N'Undergrad', NULL, N'History', 66666666)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2029, N'2020-02-28 13:21:04', N'Added', N'Eoin', N'Brosnan', N'eb@yahoo.co.uk', NULL, N'31 Quay St.', NULL, N'', NULL, N'Galway', NULL, N'Galway', NULL, N'Postgrad', NULL, N'Spanish', 76532434)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2030, N'2020-02-28 13:21:23', N'Deleted', N'Paul', N'Bridgeman', NULL, N'pb@gmail.com', NULL, N'Listowell', NULL, N'', NULL, N'', NULL, N'Kerry', NULL, N'Undergrad', N'History', 66666666)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (2031, N'2020-02-28 13:21:51', N'Updated', N'Eoin', N'Brosnan', N'eb@yahoo.co.uk', N'eb@yahoo.co.uk', N'35 Quay St.', N'31 Quay St.', N'The Quays', N'', N'Galway', N'Galway', N'Galway', N'Galway', N'Postgrad', N'Postgrad', N'Spanish', 76532434)
SET IDENTITY_INSERT [dbo].[StudentLog] OFF
