SET IDENTITY_INSERT [dbo].[Students] ON
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7023, N'Ian', N'O''Loughlin', N'iol@gmail.com', N'0872345462', N'81 Tolka Estate', N'Glasnevin', N'Dublin 11', N'Dublin', N'Postgrad', N'IT', 11111111, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7024, N'Lyn', N'O''Connor', N'lynoc@yahoo.co.uk', N'+35383-221972', N'81 Oldtown', N'Santry', N'Dublin 15', N'Dublin', N'Undergrad', N'Spanish', 22222222, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7025, N'Lily', N'O''Loughlin', N'lil@hotmail.com', N'083-221234', N'39 Sitric Rd.', N'Stoneybatter', N'Dublin 7', N'Dublin', N'Undergrad', N'Media', 33333333, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7026, N'Eoin', N'Brosnan', N'eb@yahoo.co.uk', N'01-222322', N'Kenturk', N'', N'', N'Cork', N'Undergrad', N'IT', 55555555, 1)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7027, N'Bryan', N'Mullins', N'bmul@dbs.ie', N'+353-87245234', N'43 Douglas St', N'', N'Cork', N'Cork', N'Postgrad', N'History', 55555551, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7028, N'Tony', N'Kelly', N'tk@gmail.ie', N'0834423212', N'42 Collins Avenue', N'', N'Waterford', N'Waterford', N'Postgrad', N'Media', 99999999, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (7029, N'Paul', N'Bridgeman', N'pb@ucc.ie', N'051872930', N'Newcastle West', N'', N'', N'Limerick', N'Postgrad', N'Business', 67545663, 0)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (8024, N'Jim', N'Murphy', N'jim@gmail.com', N'051887293', N'33 Hermitage', N'', N'Ennis', N'Clare', N'Undergrad', N'German', 10333330, 1)
INSERT INTO [dbo].[Students] ([Id], [FirstName], [LastName], [Email], [Phone], [AddressLine1], [AddressLine2], [City], [County], [Level], [Course], [StudentNo], [IsDeleted]) VALUES (8026, N'Conor', N'McCarthy', N'cmc@gmail.com', N'083872232', N'32 New Road', N'', N'Kilkenny', N'Kilkenny', N'Postgrad', N'Business', 54346576, 1)
SET IDENTITY_INSERT [dbo].[Students] OFF
