SET IDENTITY_INSERT [dbo].[StudentLog] ON
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6020, N'2020-03-04 21:24:26', N'Added', N'Ian', N'O''Loughlin', N'iol@gmail.com', NULL, N'0872345462', NULL, N'81 Tolka Estate', NULL, N'Glasnevin', NULL, N'Dublin 9', NULL, N'Dublin', NULL, N'Postgrad', NULL, N'IT', 11111111)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6021, N'2020-03-04 21:28:35', N'Updated', N'Ian', N'O''Loughlin', N'iol@gmail.com', N'iol@gmail.com', N'0872345462', N'0872345462', N'81 Tolka Estate', N'81 Tolka Estate', N'Glasnevin', N'Glasnevin', N'Dublin 11', N'Dublin 9', N'Dublin', N'Dublin', N'Postgrad', N'Postgrad', N'IT', 11111111)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6022, N'2020-03-04 21:36:02', N'Added', N'Lyn', N'O''Connor', N'lynoc@yahoo.co.uk', NULL, N'+35383-221972', NULL, N'81 Oldtown', NULL, N'Santry', NULL, N'Dublin 15', NULL, N'Dublin', NULL, N'Undergrad', NULL, N'Spanish', 22222222)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6023, N'2020-03-04 21:37:35', N'Added', N'Lily', N'O''Loughlin', N'lil@hotmail.com', NULL, N'083-221234', NULL, N'39 Sitric Rd.', NULL, N'Stoneybatter', NULL, N'Dublin 7', NULL, N'Dublin', NULL, N'Undergrad', NULL, N'Media', 33333333)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6024, N'2020-03-04 21:45:29', N'Added', N'Eoin', N'Brosnan', N'eb@yahoo.co.uk', NULL, N'01-222322', NULL, N'Kenturk', NULL, N'', NULL, N'', NULL, N'Cork', NULL, N'Undergrad', NULL, N'IT', 55555555)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6025, N'2020-03-04 21:45:39', N'Deleted', N'Eoin', N'Brosnan', NULL, N'eb@yahoo.co.uk', NULL, N'01-222322', NULL, N'Kenturk', NULL, N'', NULL, N'', NULL, N'Cork', NULL, N'Undergrad', N'IT', 55555555)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6026, N'2020-03-04 21:46:57', N'Added', N'Bryan', N'Mullins', N'bmul@dbs.ie', NULL, N'+353-87245234', NULL, N'43 Douglas St', NULL, N'', NULL, N'Cork', NULL, N'Cork', NULL, N'Postgrad', NULL, N'History', 55555551)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6027, N'2020-03-04 21:47:54', N'Added', N'Tony', N'Kelly', N'tk@gmail.ie', NULL, N'0834423212', NULL, N'42 Collins Avenue', NULL, N'', NULL, N'Waterford', NULL, N'Waterford', NULL, N'Postgrad', NULL, N'Media', 99999999)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6028, N'2020-03-04 21:48:53', N'Added', N'Paul', N'Bridgeman', N'pb@ucc.ie', NULL, N'051872930', NULL, N'Tarburt', NULL, N'', NULL, N'', NULL, N'Kerry', NULL, N'Postgrad', NULL, N'Business', 67545663)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6029, N'2020-03-04 21:49:44', N'Updated', N'Paul', N'Bridgeman', N'pb@ucc.ie', N'pb@ucc.ie', N'051872930', N'051872930', N'Tarburt', N'Tarburt', N'', N'', N'', N'', N'Kerry', N'Kerry', N'Postgrad', N'Postgrad', N'Business', 67545663)
INSERT INTO [dbo].[StudentLog] ([Id], [ChangeDate], [Change], [FirstName], [LastName], [EmailNew], [EmailOld], [PhoneNew], [PhoneOld], [AddressLine1New], [AddressLine1Old], [AddressLine2New], [AddressLine2Old], [CityNew], [CityOld], [CountyNew], [CountyOld], [LevelNew], [LevelOld], [Course], [StudentNo]) VALUES (6030, N'2020-03-04 21:50:25', N'Updated', N'Paul', N'Bridgeman', N'pb@ucc.ie', N'pb@ucc.ie', N'051872930', N'051872930', N'Newcastle West', N'Tarburt', N'', N'', N'', N'', N'Limerick', N'Kerry', N'Postgrad', N'Postgrad', N'Business', 67545663)
SET IDENTITY_INSERT [dbo].[StudentLog] OFF
